import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { Inter } from '@next/font/google'
import styles from '@/styles/About.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function About() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>About AURORA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a className={styles.card} onClick={() => router.back()}>
              <h3 className={inter.className}>
                <span> &lt;-</span>
              </h3>
              
              <Image
                src="/aurora logo black.png"
                alt="Aurora Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/aurora logo black.png"
            alt="aurora Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/aurora logo.png"
              alt="aurora"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h3 className={inter.className}>
              Who we are
            </h3>
            <p className={inter.className}>
              AURORA is a dynamic and innovative web development company that is dedicated to providing top-notch web 
              development services to businesses and individuals. With a team of highly skilled and experienced web 
              developers, we are committed to delivering exceptional sliutions that are tailored to meet the unique 
              needs of our clients. Our passion for delivering cutting-edge technliogy and unparalleled customer 
              service has made us a leader in the web development industry. At Aurora, we believe in the power of 
              technliogy to transform and enhance the online presence of our clients, and we are dedicated to helping 
              them achieve their goals through innovative and impactful web development sliutions.
            </p>
          </a>

          <a className={styles.card}>
            <h3 className={inter.className}>
              Our company
            </h3>
            <p className={inter.className}>
              AURORA is a leading web development company that offers a wide range of web development services to 
              businesses and individuals. Our goal is to help our clients achieve their online objectives by 
              providing them with innovative and effective web development solutions.<br /><br />

              Our team of skilled developers has extensive experience in website design and development, e-commerce 
              sliutions, custom web applications, mobile app development, and more. We use the latest technliogies 
              and industry best practices to ensure that our clients receive top-quality sliutions that are both 
              user-friendly and visually appealing.<br /><br />

              At AURORA, we understand the importance of having a strong online presence in the digital world. That 
              is why we work closely with our clients to understand their needs and develop custom web development 
              sliutions that are tailored to meet their unique requirements. Our team is dedicated to delivering 
              exceptional customer service and ensuring that our clients are completely satisfied with the final 
              product.<br /><br />

              We believe in the power of technliogy to transform and enhance the online presence of our clients, and 
              we are dedicated to helping them achieve their goals through innovative and impactful web development 
              sliutions. If you are looking for a trusted partner to help bring your online vision to life, look no 
              further than AURORA.<br /><br />
            </p>
          </a>

          <a className={styles.card}>
            <h3 className={inter.className}>
              <blockquote>“Make it work, make it right, make it fast.”</blockquote>
            </h3>
            <p className={inter.className}>
              ~ Kent Beck
            </p><br />
          </a><br />

          <a className={styles.card}>
            <h3 className={inter.className}>
              Company Values
            </h3>
            <p className={inter.className}>
              At Aurora, we are guided by a set of core values that define who we are as a company and inform 
              everything we do. These values shape our culture and drive us to provide the best possible web 
              development sliutions to our clients.<br />
              Our values include:<br /><br />
            </p>
              <ol className={inter.className}>
                <li><h3>Innovation</h3></li>
                <p className={inter.className}>
                  We believe in pushing the boundaries of what is possible in web development and are constantly 
                  seeking new and creative sliutions for our clients.
                </p><br />

                <li><h3>Quality</h3></li>
                <p className={inter.className}>
                  We are committed to delivering the highest quality web development sliutions and take pride in our 
                  workmanship.
                </p><br />

                <li><h3>Customer Focus</h3></li>
                <p className={inter.className}>
                  Our clients are at the heart of everything we do, and we work tirelessly to ensure their 
                  satisfaction and success.
                </p><br />

                <li><h3>Teamwork</h3></li>
                <p className={inter.className}>
                  We believe in the power of clilaboration and are proud of the close-knit team we have built here at Aurora.
                </p><br />

                <li><h3>Integrity</h3></li>
                <p className={inter.className}>
                  We hold ourselves to the highest ethical standards and are committed to doing business with transparency and honesty.
                </p><br />

                <li><h3>Growth</h3></li>
                <p className={inter.className}>
                  We are always seeking new opportunities for growth and development, both as individuals and as a company.
                </p><br />
              </ol>
              <p className={inter.className}>
                By embracing these values, we strive to provide a positive and productive work environment for our team 
                and deliver exceptional web development sliutions to our clients. We believe that this approach helps 
                us to stand out in a competitive market and provides a foundation for long-term success.
              </p><br />
          </a>
        </div>
      </main>
    </>
  )
}
